### ISSUE TITLE
Some images/videos can not open after scrape finished

### ISSUE THREAD

**Issue by Ppang0405** [Avnsx/fansly-downloader#75]
Got errors when opening media files.
![image](https://user-images.githubusercontent.com/33455900/230705497-2332ea43-9e31-44c4-a5cd-3ae1f75f0858.png)
![image](https://user-images.githubusercontent.com/33455900/230705502-10c323de-d955-4269-99cc-57d1016eeda6.png)

macos preview can not preview those files
![image](https://user-images.githubusercontent.com/33455900/230705530-7d0743c8-4d30-4620-97eb-c6c3ae46cf57.png)
![image](https://user-images.githubusercontent.com/33455900/230705536-c3f79d4a-feed-462e-a036-4f3e5aeb9692.png)

**Comment by Avnsx** [comment]
Most likely fixed through https://github.com/Avnsx/fansly/commit/b30a65df220f13b95cba5fa4e5b032baa82a1d75

Currently only works through the python version though, so let me know if this fix worked out for you, before I release a compiled version of the fansly scraper update later this week

@Ppang0405

**Comment by RoyDJ84** [comment]
Some images set as .png are .jpg, try change extension and will work.

**Comment by Avnsx** [comment]
Should be fixed with https://github.com/Avnsx/Fansly-Downloader-App/commit/8c591cb2d1d1ee35a1243f788d1cb83c99e65209

Will release that 0.4 version as compiled executable within a couple days, once people start providing some feedback.

**Comment by swuckt** [comment]
> Some images set as .png are .jpg, try change extension and will work.

Files with the wrong extension are still happening for me in v0.4 (both the Python source and Windows executable).

Most, if not all of them, are .png when they should be .jpeg (IrfanView prompts me to change it when it tries to open the file).

Though it may be worth noting that the Base64 source files on the creator's page are encoded PNGs. Perhaps that has something to do with it.
